name: Checks

on:
  push:
    branches:
      - main
      - release
      - develop
  pull_request:
    branches: 
      - main
      - release
      - develop
      - feature
      - hotfix

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      DATABASE_PRIMARY_HOST: localhost
      DATABASE_PRIMARY_PORT: 3306
      DATABASE_REPLICA_HOST: localhost
      DATABASE_REPLICA_PORT: 3306
      DATABASE_NAME: go-layered-architecture-sample
      DATABASE_USER: go-layered-architecture-sample
      DATABASE_PASSWORD: P@ssw0rd

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.5

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Run lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.54.2
        args: --timeout 5m

    - name: Make Up
      run: make up

    - name: Wait for database to be ready
      uses: jakejarvis/wait-action@master
      with:
        time: '15s'

    - name: Install migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate.linux-amd64 /usr/local/bin/migrate

    - name: Run migrations
      run: |
        migrate -database "mysql://go-layered-architecture-sample:P@ssw0rd@tcp(localhost:3306)/go-layered-architecture-sample" -path ./db/migrations up

    - name: Make test
      run: |
        make golden-update
        make test

    - name: Run Build
      run: make build
